### ISSUE TITLE
Issue in pushing same code in Elastic beanstalk 

### ISSUE THREAD

**Issue by swapwagh25** [swapwagh25/image-filter-starter-code-new#1]
This is my project please let me know if you are able to access it. 

https://github.com/swapwagh25/image-filter-starter-code-new.git

It is working fine if I am running locally from Postman but when I am pushing it to Elastic beanstalk I am getting error and Health state is severe

Below are few screen shots of logs 
<img width="1135" alt="Screen Shot 2019-08-15 at 9 36 00 PM" src="https://user-images.githubusercontent.com/52064832/63530338-1f9fb700-c4bb-11e9-9963-51ed8ada15f3.png">
<img width="1232" alt="Screen Shot 2019-08-15 at 9 37 34 PM" src="https://user-images.githubusercontent.com/52064832/63530339-20384d80-c4bb-11e9-94f7-20c856fff678.png">
<img width="921" alt="Screen Shot 2019-08-21 at 9 10 35 PM" src="https://user-images.githubusercontent.com/52064832/63530340-20384d80-c4bb-11e9-9d55-3a9e44517f7f.png">

**Comment by floriansalihovic** [comment]
Can you check your `/.elasticbeanstalk/config.yml`? This is mine.

```
branch-defaults:
  default:
    environment: udagram-imageserver-flosal-dev-dev
deploy:
  artifact: ./www/Archive.zip
global:
  application_name: udagram-imageserver-flosal-dev
  branch: null
  default_ec2_keyname: .aws-eb
  default_platform: Node.js
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
```
